### ISSUE TITLE
pybindgen version is empty upon configuring

### ISSUE THREAD

**Issue by ihazbackup** [named-data-ndnSIM/ndnSIM#82]
Hi, I have just started using ndnSIM and encountered the problem regarding pybindgen
I followed the setup guide from http://ndnsim.net/2.0/getting-started.html

When I configure it using 

> ./waf configure --enable-examples

Here's the result

> Setting top to                           : /Users/jasonchristian/Documents/ndnsim/ns-3 
Setting out to                           : /Users/jasonchristian/Documents/ndnsim/ns-3/build 
Checking for 'clang' (C compiler)        : /usr/bin/clang 
Checking for cc version                  : 8.0.0 
Checking for 'clang++' (C++ compiler)    : /usr/bin/clang++ 
Checking supported compiler CXXFLAGS     : -std=c++0x -std=c++11 
Checking supported optimizations CXXFLAGS : -O0 
Checking supported debug CXXFLAGS         : -ggdb -g3 
Checking supported warnings CXXFLAGS      : -Wall -Wno-error=deprecated-declarations -fstrict-aliasing -Wstrict-aliasing 
Checking for program 'python'             : /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python 
Checking for python version               : (2, 7, 14, 'final', 0) 
python-config                             : /opt/local/bin/python2.7-config 
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
Getting pyembed flags from python-config                           : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
Getting pyext flags from python-config                             : yes 
Checking for compilation flag -Wno-array-bounds... support         : ok 
Checking for pybindgen location                                    : ../pybindgen (guessed) 
Checking for python module 'pybindgen'                             : ok 
Download error on https://pypi.python.org/simple/setuptools_scm/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
Download error on https://pypi.python.org/simple/setuptools-scm/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
No local packages or working download links found for setuptools_scm
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    long_description=LONG_DESCRIPTION,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 335, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
    replace_conflicting=True,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
    replace_conflicting=replace_conflicting
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
    return self.obtain(req, installer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
    return installer(requirement)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
    return cmd.easy_install(req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
Checking for pybindgen version                                     :  
pybindgen (found ''), (need '0.17.0.post45+g4806e4f')
Checking boost includes                                            : 1_59 
Checking boost libs                                                : ok 
Checking for boost linkage                                         : ok 
Checking for click location                                        : not found 
Checking for program 'pkg-config'                                  : /opt/local/bin/pkg-config 
Checking for 'gtk+-2.0' >= 2.12                                    : yes 
Checking for 'libxml-2.0' >= 2.7                                   : yes 
Checking for type uint128_t                                        : not found 
Checking for type __uint128_t                                      : yes 
Checking high precision implementation                             : 128-bit integer (default) 
Checking for header stdint.h                                       : yes 
Checking for header inttypes.h                                     : yes 
Checking for header sys/inttypes.h                                 : not found 
Checking for header sys/types.h                                    : yes 
Checking for header sys/stat.h                                     : yes 
Checking for header dirent.h                                       : yes 
Checking for header stdlib.h                                       : yes 
Checking for header signal.h                                       : yes 
Checking for header pthread.h                                      : yes 
Checking for header stdint.h                                       : yes 
Checking for header inttypes.h                                     : yes 
Checking for header sys/inttypes.h                                 : not found 
Checking for library rt                                            : not found 
Checking for header sys/ioctl.h                                    : yes 
Checking for header net/if.h                                       : yes 
Checking for header net/ethernet.h                                 : yes 
Checking for header linux/if_tun.h                                 : not found 
Checking for header netpacket/packet.h                             : not found 
Checking for NSC location                                          : not found 
Checking for program 'doxygen'                                     : not found 
Checking for program 'tar'                                         : /usr/bin/tar 
Checking for program 'sphinx-build'                                : not found 
Checking for std::is_default_constructible                         : yes 
Checking for std::is_nothrow_move_constructible                    : yes 
Checking for std::is_nothrow_move_assignable                       : yes 
Checking for std::to_string                                        : yes 
Checking for std::vector::insert with const_iterator               : yes 
Checking for library pthread                                       : yes 
Checking for 'sqlite3'                                             : yes 
Checking Crypto++ lib                                              : 5.6.5 
Checking if CryptoPP library works                                 : yes 
Checking for OpenSSL lib                                           : "OpenSSL 1.0.2l-fips  25 May 2017" 
Checking if OpenSSL library works                                  : yes 
Checking for OpenFlow location                                     : not found 
Checking for 'sqlite3'                                             : yes 
Checking for header linux/if_tun.h                                 : not found 
Checking for program 'sudo'                                        : /usr/bin/sudo 
Checking for program 'valgrind'                                    : not found 
Checking for 'gsl'                                                 : not found 
Checking for program 'doxygen'                                     : not found 
---- Summary of optional NS-3 features:
Build profile                 : debug
Build directory               : 
Python Bindings               : not enabled (PyBindGen version not correct and newer version could not be retrieved)
BRITE Integration             : not enabled (BRITE not enabled (see option --with-brite))
NS-3 Click Integration        : not enabled (nsclick not enabled (see option --with-nsclick))
GtkConfigStore                : enabled
XmlIo                         : enabled
Threading Primitives          : enabled
Real Time Simulator           : not enabled (librt is not available)
File descriptor NetDevice     : enabled
Tap FdNetDevice               : not enabled (needs linux/if_tun.h)
Emulation FdNetDevice         : not enabled (needs netpacket/packet.h)
PlanetLab FdNetDevice         : not enabled (PlanetLab operating system not detected (see option --force-planetlab))
Network Simulation Cradle     : not enabled (NSC not found (see option --with-nsc))
MPI Support                   : not enabled (option --enable-mpi not selected)
ndnSIM                        : enabled
NS-3 OpenFlow Integration     : not enabled (OpenFlow not enabled (see option --with-openflow))
SQlite stats data output      : enabled
Tap Bridge                    : not enabled (<linux/if_tun.h> include not detected)
PyViz visualizer              : not enabled (Python Bindings are needed but not enabled)
Use sudo to set suid bit      : not enabled (option --enable-sudo not selected)
Build tests                   : not enabled (defaults to disabled)
Build examples                : enabled
GNU Scientific Library (GSL)  : not enabled (GSL not found)
'configure' finished successfully (6.708s)

The configuration is successful, but I need the visualizer enabled. The PyViz itself is not enabled due to the python binding not activated. The pybindgen module checked has strangely no version name on it.

I'm using MacOS X El Capitano 10.11.6

**Comment by ihazbackup** [comment]
I have resolved this issue just now. It seems that Python 2.7 is not configured to accept certificates by default upon executing SSL context (I don't know if the newer version has this problem or not). I ignored the HTTPS verify using this command

> PYTHONHTTPSVERIFY=0 ./waf configure --enable-examples

And it works. **setuptools_scm** is downloaded and now visualizer is enabled and can run perfectly
