### ISSUE TITLE
Problem when running an example with visualizer

### ISSUE THREAD

**Issue by RalphRebello** [named-data-ndnSIM/ndnSIM#98]
In the /ndnSIM/ns-3 folder, i execute the command ./waf --run ndn-simple --vis, it compiles, but the visual part does not load and generates this output:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ralph/Apps/ndnSIM/ns-3/src/visualizer/visualizer/__init__.py", line 2, in <module>
    from .core import start, register_plugin, set_bounds, add_initialization_hook
  File "/home/ralph/Apps/ndnSIM/ns-3/src/visualizer/visualizer/core.py", line 24, in <module>
    import ns.core
  File "/home/ralph/Apps/ndnSIM/ns-3/build/bindings/python/ns/core.py", line 5, in <module>
    from . import _core
ImportError: cannot import name _core`

**Comment by RalphRebello** [comment]
I solved this problem criating a symbolic link that point to the original librarie, inside the folder /ndnSIM/ns-3/build/bindings/python/ns/ with the name _core.so just.

Now my problem is this:
`ralph@note-ralph:~/Apps/ndnSIM/ns-3$ ./waf --run=ndn-simple --vis
Waf: Entering directory `/home/ralph/Apps/ndnSIM/ns-3/build'
Waf: Leaving directory `/home/ralph/Apps/ndnSIM/ns-3/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (17.847s)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ralph/Apps/ndnSIM/ns-3/src/visualizer/visualizer/__init__.py", line 2, in <module>
    from .core import start, register_plugin, set_bounds, add_initialization_hook
  File "/home/ralph/Apps/ndnSIM/ns-3/src/visualizer/visualizer/core.py", line 25, in <module>
    import ns.network
ImportError: No module named network`

The lib "ns.network", i dont now if the lib have some problem, or if dont have in my computer.

**Comment by zulkifll** [comment]
Try this
https://youtu.be/QJpGwynTiok 
Ubuntu 20.04 and ndnSIM 2.8
